USE [SGSO_RESCUE]
GO

DECLARE @RC int
DECLARE @NOMBRE varchar(50)
DECLARE @APELLIDO varchar(50)
DECLARE @EMAIL varchar(80)
DECLARE @DIRECCION varchar(100)
DECLARE @TELEFONO varchar(50)
DECLARE @MENSAJE varchar(150)
DECLARE @ERROR varchar(150)

-- TODO: Set parameter values here.

EXECUTE @RC = [Usuario].[INSERTA_PERSONA] 
   NULL
  ,'DAVIU'
  ,'JULIOLOTR@GMAIL.COM'
  ,'RUIZ DE ORELLANA'
  ,'70710023'
  ,@MENSAJE OUTPUT
  ,@ERROR OUTPUT


GO




